# ===================================================================
# Spring boot properties
# ===================================================================

spring:
  application:
    name: processos
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  context-path: /processos
  port: 8080

camel:
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /api/*

endpoint:
  wsdl: http://sigo-1877357518.us-east-1.elb.amazonaws.com:8088/ws/processos.wsdl
  #wsdl: http://localhost:8088/ws/processos.wsdl

logging:
  level:
    root: INFO